### ISSUE TITLE
INTERNAL_SERVER_ERROR at register query

### ISSUE THREAD

**Issue by dayrim** [juicycleff/ultimate-backend#122]
Hello. I am using docker to load up the project. Currently facing an issue with registering a user via graphql API. 
My query looks like this
```
# Write your query or mutation here
mutation register {  
  account {  
    register(input:{  
        firstname: "Alice"  
        lastname: "Bob"  
        email: "AliceBobsEmail@protonmail.com"  
        password: "supersecretpassword"  
    }) {  
      activationLink  
    }  
  }  
}  

```

Response object
```
{
  "errors": [
    {
      "message": "Cannot read property 'id' of null",
      "locations": [
        {
          "line": 3,
          "column": 5
        }
      ],
      "path": [
        "account",
        "register"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "TypeError: Cannot read property 'id' of null",
            "    at GrpcClient.getProxyService (/nest/node_modules/@nestcloud/grpc/grpc-client.js:37:35)",
            "    at Object.grpcService.<computed> [as create] (/nest/node_modules/@nestcloud/grpc/grpc-client.js:19:46)",
            "    at AccountsMutationResolver.register (/nest/dist/apps/api-admin/main.js:12770:62)",
            "    at /nest/node_modules/@nestjs/core/helpers/external-context-creator.js:68:33",
            "    at processTicksAndRejections (internal/process/task_queues.js:97:5)",
            "    at async target (/nest/node_modules/@nestjs/core/helpers/external-context-creator.js:75:28)"
          ]
        }
      }
    }
  ],
  "data": {
    "account": null
  }
}
```

Not sure if it's related but my consul docker container seems to have troubles connecting to agents
```
consul                  |     2020-06-12T13:44:43.328Z [WARN]  agent: Check socket connection failed: check=service:61c57d32688b99dc1b32ec8954384224 error="dial tcp 172.18.0.7:50054: connect: connection refused"
consul                  |     2020-06-12T13:44:43.328Z [WARN]  agent: Check is now critical: check=service:61c57d32688b99dc1b32ec8954384224
consul                  |     2020-06-12T13:44:44.458Z [WARN]  agent: Check socket connection failed: check=service:e7dbeff530ad82853d5dd9dccf9e2713 error="dial tcp 172.18.0.7:50044: connect: connection refused"
consul                  |     2020-06-12T13:44:44.458Z [WARN]  agent: Check is now critical: check=service:e7dbeff530ad82853d5dd9dccf9e2713
consul                  |     2020-06-12T13:44:45.009Z [WARN]  agent: Check socket connection failed: check=service:81e00fbd54edafc9977a46de2d83b416 error="dial tcp 172.18.0.7:45543: connect: connection refused"
consul                  |     2020-06-12T13:44:45.010Z [WARN]  agent: Check is now critical: check=service:81e00fbd54edafc9977a46de2d83b416
consul                  |     2020-06-12T13:44:48.872Z [WARN]  agent: Check socket connection failed: check=service:5758287bf77407520711c974a1aafa1e error="dial tcp 172.18.0.7:4000: connect: connection refused"
consul                  |     2020-06-12T13:44:48.873Z [WARN]  agent: Check is now critical: check=service:5758287bf77407520711c974a1aafa1e
consul                  |     2020-06-12T13:44:48.952Z [WARN]  agent: Check socket connection failed: check=service:92265306afe150a099f226b4df63b88d error="dial tcp 172.18.0.7:50089: connect: connection refused"
consul                  |     2020-06-12T13:44:48.952Z [WARN]  agent: Check is now critical: check=service:92265306afe150a099f226b4df63b88d
consul                  |     2020-06-12T13:44:52.812Z [WARN]  agent: Check socket connection failed: check=service:b9e675453a37acf83156105fe8b095f6 error="dial tcp 172.18.0.7:50052: connect: connection refused"
consul                  |     2020-06-12T13:44:52.812Z [WARN]  agent: Check is now critical: check=service:b9e675453a37acf83156105fe8b095f6
consul                  |     2020-06-12T13:44:53.330Z [WARN]  agent: Check socket connection failed: check=service:61c57d32688b99dc1b32ec8954384224 error="dial tcp 172.18.0.7:50054: connect: connection refused"
consul                  |     2020-06-12T13:44:53.330Z [WARN]  agent: Check is now critical: check=service:61c57d32688b99dc1b32ec8954384224

```

Any ideas what cause this ?

**Comment by dyllanwli** [comment]
Got the same problem here, everything works fine until yesterday.

**Comment by dyllanwli** [comment]
It seems those port not listening. But the api still can call grpc and pass the params to the account service. Then user info is updated to the mongo.

**Comment by juicycleff** [comment]
@dayrim this happens when your services are not communicating correctly through the consul registry

**Comment by juicycleff** [comment]
This is mostly a local consul issue
