### ISSUE TITLE
TypeError: stripe_1.default is not a constructor

### ISSUE THREAD

**Issue by dayrim** [juicycleff/ultimate-backend#123]
Hello, i get `TypeError: stripe_1.default is not a constructor` error when starting service-billing. It seems to have something to do either with import or with stripe types in nestjs-stripe package.
```
service-billing_1       | [Nest] 1   - 06/13/2020, 4:50:28 AM   [NestFactory] Starting Nest application...
service-billing_1       | [Nest] 1   - 06/13/2020, 4:50:28 AM   [InstanceLoader] ServiceRegistryModule dependencies initialized +83ms
service-billing_1       | [Nest] 1   - 06/13/2020, 4:50:28 AM   [InstanceLoader] LoggerModule dependencies initialized +1ms
service-billing_1       | [Nest] 1   - 06/13/2020, 4:50:28 AM   [InstanceLoader] ScheduleModule dependencies initialized +0ms
service-billing_1       | [Nest] 1   - 06/13/2020, 4:50:28 AM   [InstanceLoader] BootModule dependencies initialized +0ms
service-billing_1       | [Nest] 1   - 06/13/2020, 4:50:28 AM   [InstanceLoader] MemcachedModule dependencies initialized +1ms
service-billing_1       | [Nest] 1   - 06/13/2020, 4:50:28 AM   [InstanceLoader] EventStoreModule dependencies initialized +0ms
service-billing_1       | [Nest] 1   - 06/13/2020, 4:50:28 AM   [InstanceLoader] CommonModule dependencies initialized +0ms
service-billing_1       | [Nest] 1   - 06/13/2020, 4:50:28 AM   [InstanceLoader] CoreModule dependencies initialized +1ms
service-billing_1       | [Nest] 1   - 06/13/2020, 4:50:28 AM   [InstanceLoader] MongoModule dependencies initialized +0ms
service-billing_1       | [Nest] 1   - 06/13/2020, 4:50:28 AM   [InstanceLoader] StripeModule dependencies initialized +1ms
service-billing_1       | [Nest] 1   - 06/13/2020, 4:50:28 AM   [InstanceLoader] EventStoreModule dependencies initialized +1ms
service-billing_1       | [Nest] 1   - 06/13/2020, 4:50:28 AM   [InstanceLoader] HttpModule dependencies initialized +4ms
service-billing_1       | [Nest] 1   - 06/13/2020, 4:50:28 AM   [InstanceLoader] AppModule dependencies initialized +1ms
service-billing_1       | [Nest] 1   - 06/13/2020, 4:50:28 AM   [InstanceLoader] ConsulModule dependencies initialized +1ms
service-billing_1       | [Nest] 1   - 06/13/2020, 4:50:28 AM   [InstanceLoader] CqrsModule dependencies initialized +10ms
service-billing_1       | [Nest] 1   - 06/13/2020, 4:50:28 AM   [ConfigModule] ConfigModule initialized
service-billing_1       | [Nest] 1   - 06/13/2020, 4:50:28 AM   [InstanceLoader] ConfigModule dependencies initialized +1ms
service-billing_1       | [Nest] 1   - 06/13/2020, 4:50:28 AM   [ExceptionHandler] stripe_1.default is not a constructor +18ms
service-billing_1       | TypeError: stripe_1.default is not a constructor
service-billing_1       |     at Object.getStripeClient (/nest/node_modules/nestjs-stripe/lib/util/getStripeClient.js:22:26)
service-billing_1       |     at InstanceWrapper.useFactory [as metatype] (/nest/node_modules/nestjs-stripe/lib/StripeCoreModule.js:27:51)
service-billing_1       |     at Injector.instantiateClass (/nest/node_modules/@nestjs/core/injector/injector.js:292:55)
service-billing_1       |     at callback (/nest/node_modules/@nestjs/core/injector/injector.js:76:41)
service-billing_1       |     at processTicksAndRejections (internal/process/task_queues.js:97:5)
service-billing_1       |     at async Injector.resolveConstructorParams (/nest/node_modules/@nestjs/core/injector/injector.js:117:24)
service-billing_1       |     at async Injector.loadInstance (/nest/node_modules/@nestjs/core/injector/injector.js:80:9)
service-billing_1       |     at async Injector.loadProvider (/nest/node_modules/@nestjs/core/injector/injector.js:37:9)
service-billing_1       |     at async Promise.all (index 5)
service-billing_1       |     at async InstanceLoader.createInstancesOfProviders (/nest/node_modules/@nestjs/core/injector/instance-loader.js:42:9)
service-billing_1       |     at async /nest/node_modules/@nestjs/core/injector/instance-loader.js:27:13
service-billing_1       |     at async Promise.all (index 21)
service-billing_1       |     at async InstanceLoader.createInstances (/nest/node_modules/@nestjs/core/injector/instance-loader.js:26:9)
service-billing_1       |     at async InstanceLoader.createInstancesOfDependencies (/nest/node_modules/@nestjs/core/injector/instance-loader.js:16:9)
service-billing_1       |     at async /nest/node_modules/@nestjs/core/nest-factory.js:81:17
service-billing_1       |     at async Function.asyncRun (/nest/node_modules/@nestjs/core/errors/exceptions-zone.js:17:13)

```

**Comment by juicycleff** [comment]
@dayrim fixed
