### ISSUE TITLE
 Schema must contain uniquely named types but contains multiple types named "EmailObject".

### ISSUE THREAD

**Issue by dayrim** [juicycleff/ultimate-backend#124]
Hello. There is an error while running api-admin service regarding the EmailObject type. 
Any possible fixes ?
```
(node:3244) UnhandledPromiseRejectionWarning: Error: Schema must contain uniquely named types but contains multiple types named "EmailObject".
    at new GraphQLSchema (C:\Users\msi4\apps\ultimate-backend\node_modules\graphql\type\schema.js:194:15)
    at GraphQLSchemaFactory.<anonymous> (C:\Users\msi4\apps\ultimate-backend\node_modules\@nestjs\graphql\dist\schema-builder\graphql-schema.factory.js:41:32)
    at Generator.next (<anonymous>)
    at C:\Users\msi4\apps\ultimate-backend\node_modules\@nestjs\graphql\node_modules\tslib\tslib.js:114:75
    at new Promise (<anonymous>)
    at Object.__awaiter (C:\Users\msi4\apps\ultimate-backend\node_modules\@nestjs\graphql\node_modules\tslib\tslib.js:110:16)
    at GraphQLSchemaFactory.create (C:\Users\msi4\apps\ultimate-backend\node_modules\@nestjs\graphql\dist\schema-builder\graphql-schema.factory.js:30:28)
    at GraphQLSchemaBuilder.<anonymous> (C:\Users\msi4\apps\ultimate-backend\node_modules\@nestjs\graphql\dist\graphql-schema.builder.js:57:60)
    at Generator.next (<anonymous>)
    at C:\Users\msi4\apps\ultimate-backend\node_modules\@nestjs\graphql\node_modules\tslib\tslib.js:114:75
    at new Promise (<anonymous>)
    at Object.__awaiter (C:\Users\msi4\apps\ultimate-backend\node_modules\@nestjs\graphql\node_modules\tslib\tslib.js:110:16)
    at GraphQLSchemaBuilder.buildSchema (C:\Users\msi4\apps\ultimate-backend\node_modules\@nestjs\graphql\dist\graphql-schema.builder.js:56:28)
    at GraphQLSchemaBuilder.<anonymous> (C:\Users\msi4\apps\ultimate-backend\node_modules\@nestjs\graphql\dist\graphql-schema.builder.js:26:39)
    at Generator.next (<anonymous>)
    at C:\Users\msi4\apps\ultimate-backend\node_modules\@nestjs\graphql\node_modules\tslib\tslib.js:114:75
(node:3244) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:3244) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Relevant issues
https://github.com/MichalLytek/type-graphql/issues/396
https://github.com/nestjs/graphql/issues/721

**Comment by dayrim** [comment]
Tried to generate schema.gql file. The only places when EmailObject is specified are
```
type User {
  id: ID!
  createdAt: DateTime!
  updatedAt: DateTime!
  firstname: String!
  lastname: String!
  roles: [String!]!
  primaryEmail: String!
  emails: [EmailObject!]!
}
type EmailObject {
  address: String!
  primary: Boolean!
  verified: Boolean!
}
```
So it seems fine.

**Comment by dayrim** [comment]
Tried to delete EmailObject from user.type.ts It's showing the same error for a User type instead. Weird.

**Comment by dayrim** [comment]
Edit:
Rolling back to https://github.com/juicycleff/ultimate-backend/commit/1992a4c8bb226a48f65f44e633a8914a5365f037 commit actually worked.

**Comment by dayrim** [comment]
Found it ! :D Turned out very simple. There are duplicate GraphQLModule imports.

```
import { Module } from '@nestjs/common';
import { GraphQLModule } from '@nestjs/graphql';
import { CookieSerializer } from '@ultimatebackend/common';
import { CoreModule, RolesRpcClientService, ServiceRegistryModule } from '@ultimatebackend/core';
import { AppController } from './app.controller';
import { AppService } from './app.service';
import { RolesModule } from './roles/roles.module';
import { AccountsModule } from './accounts/accounts.module';
import { TenantsModule } from './tenants/tenants.module';
import { WebhooksModule } from './webhooks/webhooks.module';
import { BillingsModule } from './billings/billings.module';
import { CardsModule } from './cards/cards.module';
import { PlansModule } from './plans/plans.module';
import { NotificationsModule } from './notifications/notifications.module';
import { UsersModule } from './users/users.module';
import { TenantMembersModule } from './tenant-members/tenant-members.module';
import { GqlConfigService } from './gql-config.service';
import { AccessTokenModule } from './access-token/access-token.module';
import { GlobalClientModule } from './common/global-client.module';

@Module({
  imports: [
    ServiceRegistryModule,
    GraphQLModule.forRootAsync({
      useClass: GqlConfigService,
    }),
    GraphQLModule.forRootAsync({
      useClass: GqlConfigService,
    }),
    GlobalClientModule,
    CoreModule,
    RolesModule,
    AccountsModule,
    TenantsModule,
    WebhooksModule,
    BillingsModule,
    CardsModule,
    PlansModule,
    NotificationsModule,
    UsersModule,
    TenantMembersModule,
    AccessTokenModule,
  ],
  controllers: [AppController],
  providers: [AppService, CookieSerializer, RolesRpcClientService],
})
export class AppModule {}
```

**Comment by juicycleff** [comment]
@dayrim Yes, I saw this issue. I will fix it asap. It's weird ho it came out

**Comment by juicycleff** [comment]
Done :)
