### ISSUE TITLE
Cannot set headers after they are sent to the client

### ISSUE THREAD

**Issue by dayrim** [juicycleff/ultimate-backend#125]
Hello i reduced the code for login page to this.
```Typescript
  @ResolveField(() => Account)
  async login(
    @Args("input") { service, params }: LoginInput,
    @Context() context: any
  ): Promise<Account> {
    const auth = await context.authenticate("graphql-local", {
      email: params.email,
      password: params.password,
    });
    context.login(auth.user);
    return {
      id: auth.user.id,
      user: auth.user,
    };
  }
```
Yet still i receive and error when i try to login the user. The error disappears when i remove context.login(auth.user) function.

```
(node:432) UnhandledPromiseRejectionWarning: Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client

at ServerResponse.setHeader (_http_outgoing.js:518:11)

at ServerResponse.header (/ftw/node_modules/express/lib/response.js:771:10)

at ServerResponse.send (/ftw/node_modules/express/lib/response.js:170:12)

at ServerResponse.json (/ftw/node_modules/express/lib/response.js:267:15)

at ExpressAdapter.reply (/ftw/node_modules/@nestjs/platform-express/adapters/express-adapter.js:24:57)

at ExceptionsHandler.handleUnknownError (/ftw/node_modules/@nestjs/core/exceptions/base-exception-filter.js:33:24)

at ExceptionsHandler.catch (/ftw/node_modules/@nestjs/core/exceptions/base-exception-filter.js:17:25)

at ExceptionsHandler.next (/ftw/node_modules/@nestjs/core/exceptions/exceptions-handler.js:16:20)

at /ftw/node_modules/@nestjs/core/router/router-proxy.js:24:35

at Layer.handle_error (/ftw/node_modules/express/lib/router/layer.js:71:5)

at trim_prefix (/ftw/node_modules/express/lib/router/index.js:315:13)

at /ftw/node_modules/express/lib/router/index.js:284:7

at Function.process_params (/ftw/node_modules/express/lib/router/index.js:335:12)

at next (/ftw/node_modules/express/lib/router/index.js:275:10)

at Layer.handle_error (/ftw/node_modules/express/lib/router/layer.js:67:12)

at trim_prefix (/ftw/node_modules/express/lib/router/index.js:315:13)

(node:432) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)

(node:432) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

What might cause the error ?

**Comment by juicycleff** [comment]
@dayrim this not really clear why that error happens. Might be good to probe it
