### ISSUE TITLE
Cannot return null for non-nullable field AuthPayload.tokens.

### ISSUE THREAD

**Issue by av8ta** [juicycleff/ultimate-backend#65]
Error while attempting to login

Probably not a bug; I'm not sure I understand yet what I'm supposed to do to login from graphql playground.

I registered with the register mutation

```graphql
mutation register {
  register(input:{
    firstname: "firstname"
    lastname: "lastname"
    email: "emailaddressiused@protonmail.com"
    password: "supersecretpassword"
  }) {
    success
  }
}
```

which replied with ```success: true```

Then verified email with

```graphql
mutation verifyEmail {
  verifyEmail(token: tokenfromsignupemail, email: "emailaddressiused@protonmail.com") {
    success
  }
}
```
which also replied success. However when I go to login like

```graphql
mutation login {
  login(input:{
    service: Password
    params:{
      password: "supersecretpassword"
      email: "emailaddressiused@protonmail.com"
    }
  }) {
    id
    sessionId
    tokens {
      refreshToken
      accessToken
    }
  }
}
```

... I get the following error:

```
{
  "errors": [
    {
      "message": "Cannot return null for non-nullable field AuthPayload.tokens.",
      "path": [
        "login",
        "tokens"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "serviceName": "auth",
        "query": "mutation {\n  login(input: {service: Password, params: {password: \"supersecretpasswordiused\", email: \"emailaddressiused@protonmail.com\"}}) {\n    id\n    sessionId\n    tokens {\n      refreshToken\n      accessToken\n    }\n  }\n}",
        "variables": {},
        "exception": {
          "stacktrace": [
            "Error: Cannot return null for non-nullable field AuthPayload.tokens.",
            "    at completeValue (/home/av8ta/code/ultimate-backend/node_modules/graphql/execution/execute.js:560:13)",
            "    at completeValueCatchingError (/home/av8ta/code/ultimate-backend/node_modules/graphql/execution/execute.js:495:19)",
            "    at resolveField (/home/av8ta/code/ultimate-backend/node_modules/graphql/execution/execute.js:435:10)",
            "    at executeFields (/home/av8ta/code/ultimate-backend/node_modules/graphql/execution/execute.js:275:18)",
            "    at collectAndExecuteSubfields (/home/av8ta/code/ultimate-backend/node_modules/graphql/execution/execute.js:713:10)",
            "    at completeObjectValue (/home/av8ta/code/ultimate-backend/node_modules/graphql/execution/execute.js:703:10)",
            "    at completeValue (/home/av8ta/code/ultimate-backend/node_modules/graphql/execution/execute.js:591:12)",
            "    at completeValue (/home/av8ta/code/ultimate-backend/node_modules/graphql/execution/execute.js:557:21)",
            "    at /home/av8ta/code/ultimate-backend/node_modules/graphql/execution/execute.js:492:16",
            "    at runMicrotasks (<anonymous>)"
          ]
        }
      }
    }
  ],
  "data": null
}
```

But a few seconds later I get a User Logged In email. So I try a query:

```graphql
query me {
  me {
    firstname
  }
}
```

Which unsurprisingly returns an error:

```
{
  "errors": [
    {
      "message": "Cannot return null for non-nullable field User.firstname.",
...
```

Not sure what I'm doing wrong here?

**Comment by av8ta** [comment]
@juicycleff I see there's a session.app cookie, do I need to do something with that when I run the mutation login?

Or pass the accessToken or accessTokenSecret? Just not sure what I'm meant to do here in the graphql playground to login!

**Comment by juicycleff** [comment]
@av8ta I will update the AuthPayload type, You don't need any response really, because it uses session

```Graphql
mutation login {
  login(input:{
    service: Password
    params:{
      password: "supersecretpassword"
      email: "emailaddressiused@protonmail.com"
    }
  }) {
    id
  }
}
```

**Comment by juicycleff** [comment]
Those fields are by default null an also marked as required. They were added to support JWT token authentication too

**Comment by juicycleff** [comment]
@av8ta I updated the fix

**Comment by av8ta** [comment]
> Those fields are by default null an also marked as required. They were added to support JWT token authentication too which is in the roadmap

Ah! I understand now, thanks! It's working fine for me now if I return the id and sessionId, thanks heaps :)
