### ISSUE TITLE
Runtime Error (service-notification) : EmailModule BRPOPLPUSH ReplyError

### ISSUE THREAD

**Issue by shajeeck** [juicycleff/ultimate-backend#85]
**version : 2.0.0-alpha.2**

`nest start service-notification` gives an error after startup from EmailModule

> BRPOPLPUSH ReplyError: READONLY You can't write against a read only replica.
    at parseError (D:\Projects\iBAP-Omnicom\NEST\ultimate-backend\node_modules\redis-parser\lib\parser.js:179:12)
    at parseType (D:\Projects\iBAP-Omnicom\NEST\ultimate-backend\node_modules\redis-parser\lib\parser.js:302:14) {
  command: {
    name: 'brpoplpush',
    args: [
      'bull:notification_queue:wait',
      'bull:notification_queue:active',
      '5'
    ]
  }
}

**Comment by juicycleff** [comment]
@shajeeck that has to do with your local redis instance
